[package]
name = "org_blog"
version = "0.1.0"
authors = ["lichong <lc@molasync.com>"]

[dependencies]
staticfile = "*"
iron = "*"
mount = "*"
router = "*"
logger = "*"
bodyparser = "*"
urlencoded = "*"