[package]
name = "org_blog"
version = "0.1.0"
authors = ["lichong <lc@molasync.com>"]

[dependencies]
iron = "*"
mount = "*"
router = "*"
logger = "*"
bodyparser = "*"
urlencoded = "*"
serde = "*"
serde_json = "*"

[dependencies.staticfile]
version = "*"
features = ["cache"]
